### ISSUE TITLE
Naming convention for packer address

### ISSUE THREAD

**Issue by youzi** [vigour-io/ferry#13]
Instead of naming the url, something like:
`mtv-develop.vigour.io`,
which follows this convention: `<short-project-name>-<branch-name>.vigour.io`,
I propose we follow a more strict convention, like:`<exact-repo-name>-<branch-name>.vigour.io`

Although this will result in slightly longer url's, you will never have to worry about a namespace being taken, plus the url will be a 100% predictable.

I want to verify this with @jimdebeer and @marcusbesjes, before executing

**Comment by shawninder** [comment]
This is not the packer's responsibility, it's up to whoever (or rather **what**ever) is launching the packer
