### ISSUE TITLE
Update MTV Packer for new JSON-LD structure

### ISSUE THREAD

**Issue by shawninder** [vigour-io/ferry#38]
_From @ricksmitvigour on April 4, 2016 8:9_

For serving meta data we use a set of JSON-LD's that corresponds with the requested page, in the current setup we only serve english title and descriptions, and we would like to display other languages as well.

The JSON-LD's will have the following structure [language-code][franchise-id].[season-number][episode-number] e.g. nl.977.2.1

When the packer gets a request where the url is appended with a language code, it needs to serve the corresponding JSON-LD.

_Copied from original issue: vigour-io/packer-server#43_

**Comment by shawninder** [comment]
@ricksmitvigour I'm guessing you mean `[language-code].[franchise-id].[season-number].[episode-number]`.

Do we still want the `shows.` prefix?

That is to say, the current json ld files look like this:

- channels.json
- discover.json
- shows.1043.1.1.json
- ...

And now they would look like this? :
- nl.channels.json
- nl.discover.json
- nl.shows.1043.1.1.json
- ...

Or do you have something else in mind?

**Comment by shawninder** [comment]
Also, we're going to need to synchronize updating the ferries and putting the new files with their new names to a period of time where we don't have the data... Let's plan a time to do it together @ricksmitvigour

**Comment by shawninder** [comment]
The ferry is going to need a way to know which region to use. What's the plan for this?

**Comment by ricksmitvigour** [comment]
That's in the language-code, I'll come by later to synchronise.

**Comment by shawninder** [comment]
I'm not sure I understand. Where do I get the language-code from to know which `.json` file to get the info from?

**Comment by shawninder** [comment]
TODO

- [ ] Fetch the JSON LD files from a remote server via http instead of expecting them to be in the repo of the app served by ferry
- [ ] Rerun the meta transform regularly in addition to running it on launch and on updates, or maybe only run it on crawler requests..
- [ ] test it and also make sure the fb stuff doesn't break if we remove the json ld files from the mtv-play repo...

**Comment by shawninder** [comment]
This is all done on develop

Next step is to do it for staging, and eventually, on production

**Comment by shawninder** [comment]
@ricksmitvigour This is now pushed to production. When you think you've tested it enough, feel free to close this issue :)
